# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da1df1e7cb013aaf7107ee59dabe2ee44acfea273f9f0255883649427ca580a5c18de75d317b84bf10ebda43a00748fab08511b97e7d9b06f1cd58a471135a95

test:
  secret_key_base: dfdf39f0bb4463ac218dac79cb8468ff6d8770eea17662ea03278d9942db3c5ae2343ffb6ea21031358cc6104b1338f3efa6e0766e7a279ce3bc9f384d13f5c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
